[package]
name = "sqlite-wasm-vfs"
version = "0.3.0"
edition = "2021"
rust-version.workspace = true
readme = "README.md"
authors = ["Spxg <noz@live.com>"]
license = "MIT"
repository = "https://github.com/Spxg/sqlite-wasm-rs"
description = "SQLite VFS implementations for wasm32-unknown-unknown."
categories = ["development-tools::ffi", "wasm", "database"]
keywords = ["sqlite", "sqlite-wasm", "wasm", "webassembly", "javascript"]

[features]
opfs-jspi = [
  "dep:rsqlite-vfs",
  "dep:wasm-bindgen",
  "dep:js-sys",
  "dep:thiserror",
  "dep:async-lock",
]
sahpool = [
  "dep:rsqlite-vfs",
  "dep:wasm-bindgen",
  "dep:js-sys",
  "dep:futures-util",
  "dep:thiserror",
  "dep:web-sys",
]

[dependencies]
rsqlite-vfs = { version = "0.2", optional = true }

wasm-bindgen = { version = "0.2.128", default-features = false, optional = true }
js-sys = { version = "0.3.105", default-features = false, features = ["std"], optional = true }
futures-util = { version = "0.3.34", default-features = false, features = ["std"], optional = true }
thiserror = { version = "2.0.20", default-features = false, optional = true }
async-lock = { version = "3.4", default-features = false, optional = true }
web-sys = { version = "0.3.105", default-features = false, optional = true, features = [
  "StorageManager",
  "FileSystemSyncAccessHandle",
  "FileSystemDirectoryHandle",
  "FileSystemGetDirectoryOptions",
  "FileSystemReadWriteOptions",
  "DedicatedWorkerGlobalScope",
  "WorkerNavigator",
  "FileSystemGetFileOptions",
  "FileSystemFileHandle",
]}

[dev-dependencies]
wasm-bindgen-test = "0.3.78"
sqlite-wasm-rs = { version = "0.6", default-features = false, features = ["wasm-bindgen"] }

[[test]]
name = "sahpool"
required-features = ["sahpool"]

[package.metadata.docs.rs]
all-features = true
targets = ["wasm32-unknown-unknown"]
