[package]
name = "opfs-jspi-example"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
sqlite-wasm-rs = { path = "../..", features = ["wasm-bindgen"] }
sqlite-wasm-vfs = { path = "../../crates/sqlite-wasm-vfs", features = ["opfs-jspi"] }
rsqlite-vfs = { path = "../../crates/rsqlite-vfs" }
wasm-bindgen = "0.2.128"
js-sys = "0.3.105"

[package.metadata.wasm-pack.profile.release]
wasm-opt = false
